export enum UserActionTypes {
    LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST',
    LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE',
    LOGOUT_USER = 'LOGOUT_USER',
    LOGIN_CLEAR_ERROR = 'LOGIN_CLEAR_ERROR',
}